### ISSUE TITLE
Unnecessary OperatorFilterer1155

### ISSUE THREAD

**Issue by cygaar** [ProjectOpenSea/operator-filter-registry#11]
I don't think it's necessary to have a separate filterer class for 1155. I presume the goal of OperatorFilterer1155.sol was to demonstrate what a 1155 filterer would look like, but the current example doesn't showcase anything different than the 721 filterer. Looping multiple times here without using the `ids` parameter seems unnecessary: https://github.com/ProjectOpenSea/operator-filter-registry/blob/main/src/example/OperatorFilterer1155.sol#L42. Additionally, the `id` parameter here is unused: https://github.com/ProjectOpenSea/operator-filter-registry/blob/main/src/example/OperatorFilterer1155.sol#L29.

I'm also trying to think of a scenario in which a certain 1155 id would need to be blocked, but another wouldn't be.

**Comment by operatorfilterer** [comment]
Thanks – this was related to a redundant balance check that has since been removed. We can merge the two back together.

**Comment by operatorfilterer** [comment]
Done, and thanks! Let us know if you have more questions
