### ISSUE TITLE
How to Test in Hardhat?

### ISSUE THREAD

**Issue by zdenham** [ProjectOpenSea/operator-filter-registry#114]
We are trying to test the operator filter to ensure royalty enforcement will work in our smart contracts.

We are using `UpgradeableRevokable` but it seems the registry is hard coded to an address with no way to update it, so we can't deploy a mock registry to see if the thing works.

Curious how do people test this locally?

**Comment by ryanio** [comment]
In hardhat you can setCode to an address, so would recommend deploying it to there

**Comment by zdenham** [comment]
Oh nice! TIL, here is reference [docs](https://hardhat.org/hardhat-network-helpers/docs/reference#setcode(address,-code)) if anyone else comes across this.

I will say, hard coding these constants feels a bit odd, why not have internal funcs which return the constants but are overridable? 

Would be some gas cost for jump ops but seems worth the flexibility 🤷🏼‍♂️

**Comment by zdenham** [comment]
Thanks anyhow for the help @ryanio 🙏
