### ISSUE TITLE
Multichain support / deploys

### ISSUE THREAD

**Issue by nfts2me** [ProjectOpenSea/operator-filter-registry#12]
Currently Operator Filter Registry is just deployed on Ethereum and Goerli at 0x000000000000aaeb6d7670e522a718067333cd4e.

We could deploy our own registries in different networks, but it makes sense to have one unique registry address (0x000000000000aaeb6d7670e522a718067333cd4e) deployed across different blockchains.

It would be great to have full support (including filtered addresses) on the networks you already support: Arbitrum, Avalanche, Klaytn, Optimism, Polygon, Solana.
But at least and empty deployment on EVM Blockchains would ease things for multichain projects like ours, where we can share code across different blockchains and not having to think about different addresses on different blockchains and keeping our own registries. 
  
We've implement it from the very first day at https://nfts2me.com/ (https://twitter.com/nfts2me/status/1589215568942747648) as we think this is a great option for creators, but support for other blockchain is really a need!

**Comment by nfts2me** [comment]
> We'll be deploying to other networks in the coming days, and will update the readme accordingly. In the meantime, anyone can deploy to an EVM chain that has the [Immutable Create2 Factory](https://github.com/ProjectOpenSea/seaport/blob/main/docs/Deployment.md#setting-up-factory-on-a-new-chain) already deployed using [the deploy script](https://github.com/ProjectOpenSea/operator-filter-registry/blob/main/script/DeployRegistry.s.sol).

Thank you for the response!
I didn't know about 0x0000000000FFe8B47B3e2130213B802212439497 from @0age from your team.
Is there a list with all the deployed networks where it is deployed?
Well..., actually I should actually say 0x7a0d94f55792c434d74a40883c6ed8545e406d12? If I'm not mistaken, the root parent of the other create2 factories.

**Comment by Slokh** [comment]
> > We'll be deploying to other networks in the coming days, and will update the readme accordingly. In the meantime, anyone can deploy to an EVM chain that has the [Immutable Create2 Factory](https://github.com/ProjectOpenSea/seaport/blob/main/docs/Deployment.md#setting-up-factory-on-a-new-chain) already deployed using [the deploy script](https://github.com/ProjectOpenSea/operator-filter-registry/blob/main/script/DeployRegistry.s.sol).
> 
> Thank you for the response! I didn't know about 0x0000000000FFe8B47B3e2130213B802212439497 from @0age from your team. Is there a list with all the deployed networks where it is deployed? Well..., actually I should actually say 0x7a0d94f55792c434d74a40883c6ed8545e406d12? If I'm not mistaken, the root parent of the other create2 factories.

The factory is deployed on all chains OpenSea supports and some additional ones, not sure if the full list is documented somewhere.

**Comment by dziugasmeskauskas** [comment]
@Slokh Any ETA on the polygon contract?

**Comment by nfts2me** [comment]
I've seen multichain deployments! Thank you!

The only missing thing is the curated list.

**Comment by ihorbond** [comment]
> @Slokh Any ETA on the polygon contract?

it's the same address on Polygon for the DefaultFilterer. it works.

**Comment by operatorfilterer** [comment]
Many chains were added in #39 - with more to be added over time for future-proofing.

As of now, the only chain with a curated list is Mainnet Ethereum, which Göerli reflects so creators can test before deploying.

We are still in the process of evaluating the landscape of marketplaces on other chains.
