### ISSUE TITLE
Contracts on Goerli are incorrectly failing validation

### ISSUE THREAD

**Issue by itsanishjain** [ProjectOpenSea/operator-filter-registry#18]
![Screenshot from 2022-11-11 00-21-46](https://user-images.githubusercontent.com/43033153/201181517-f7d184bc-72a5-4f6a-a86d-04bfa64c225e.png)

Hey Deploy the contract on Goerli network. 

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

import {ERC721} from "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";
import {DefaultOperatorFilterer} from "./DefaultOperatorFilterer.sol";

contract NFTee is ERC721, DefaultOperatorFilterer, Ownable {


    constructor() ERC721("Example", "EXAMPLE") {
        _mint("YOUR_TREASURY_ADDRESS",1);
    }

    function transferFrom(address from, address to, uint256 tokenId) public override onlyAllowedOperator(from) {
        super.transferFrom(from, to, tokenId);
    }

    function safeTransferFrom(address from, address to, uint256 tokenId) public override onlyAllowedOperator(from) {
        super.safeTransferFrom(from, to, tokenId);
    }

    function safeTransferFrom(address from, address to, uint256 tokenId, bytes memory data)
        public
        override
        onlyAllowedOperator(from)
    {
        super.safeTransferFrom(from, to, tokenId, data);
    }

    function tokenURI(uint256) public pure override returns (string memory) {
        return "";
    }
}

```

**Comment by itsanishjain** [comment]
Is it because Contract is deploy on Goerli and Operator Registry contracts are not yet there

**Comment by timvaniersel** [comment]
Got the same on mainnet, trying to find a collection that has it implemented and is receiving royalties.

**Comment by timvaniersel** [comment]
Could verify with other recently launched collections they're experiencing the same issue and do have it implemented.

**Comment by iainnash** [comment]
You need a valid tokenURI for this to work. Add a valid tokenURI and it should work. I ran into the same issue.

**Comment by iainnash** [comment]
See #20

**Comment by Slokh** [comment]
Can you link addresses? We did have a misconfiguration issue that has been resolved so theoretically should work now.

**Comment by mi-yu** [comment]
@Slokh experiencing the same issue with a new collection on goerli: `0xfc18ffefe496fca1d0a99f6486c38306357c28ed`

**Comment by Slokh** [comment]
@mi-yu you did not apply the modifier in your contract `onlyAllowedOperator`

**Comment by mi-yu** [comment]
ah missed that, thanks!

**Comment by itsanishjain** [comment]
> You need a valid tokenURI for this to work. Add a valid tokenURI and it should work. I ran into the same issue.

It is not working with that too, I already checked with that

**Comment by itsanishjain** [comment]
The contract is not verified 
but here is the open sea link
https://testnets.opensea.io/collection/soul-3p25qxruh8

**Comment by itsanishjain** [comment]
@Slokh what "misconfiguration"

**Comment by itsanishjain** [comment]
> Got the same on mainnet, trying to find a collection that has it implemented and is receiving royalties.

Hey #20 is the answer

**Comment by Chkhikvadze** [comment]
I have the same issue with my contract https://goerli.etherscan.io/address/0xdaa48d1360a67be41743ca1a3d09e0d948a83674#readContract

**Comment by operatorfilterer** [comment]
Ingestion on Goerli should be fixed for new contracts - if your contract is still displaying as ineligible, please share your address and we can re-validate, thanks!

**Comment by augustfr** [comment]
Does this contract just need to be re-validated? This is an attempt I made a couple of days ago with the revokable filterer and using the tinyerc721 implementation. 

https://goerli.etherscan.io/address/0x07B31f97499a071be4C82080C64De43150082bAE

Let me know if there is something wrong

**Comment by ihorbond** [comment]
if it helps provide any clarity: I've successfully extended both ERC721 and ERC721A contracts with necessary overrides and creator fees are working on Goerli.

**Comment by pictta-mac** [comment]
Hello @operatorfilterer could you please help on re-validating this contract please? Thanks
https://goerli.etherscan.io/address/0xceeab5b8852e267a27f51799d892bad86e3baadd#code#F11#L1

**Comment by Slokh** [comment]
> Hello @operatorfilterer could you please help on re-validating this contract please? Thanks https://goerli.etherscan.io/address/0xceeab5b8852e267a27f51799d892bad86e3baadd#code#F11#L1

a mint needs to happen first

**Comment by 0xfcks** [comment]
Im working on adding the Operator Filter Registry modifiers to my ERC721A-Upgradeable Diamond contract. I followed the instructions on https://github.com/ProjectOpenSea/operator-filter-registry/issues/32 but I still see the optional creators earnings on OpenSea testnet:

<img width="1389" alt="image" src="https://github.com/ProjectOpenSea/operator-filter-registry/assets/98991098/73847f97-d15e-4020-a66a-9aa686933b03">

Here is my implementation contract that inherits from ERC721A-Upgradeable: https://goerli.etherscan.io/address/0x5D8db24BBbb93fc9893bf04C4e8C2D0AC623535B#code

And here is the diamond contract address: 0x2342C51661D8C4619C174D86F1268820C22C1aac

Any help on why OpenSea does not recognize my Operator Filter Registry modifiers would be great! Thanks!
