### ISSUE TITLE
Creator fee information not being ingested from `contractURI` method

### ISSUE THREAD

**Issue by ashrhmn** [ProjectOpenSea/operator-filter-registry#27]
I am trying to deploy a contract with the creator earnings embedded into the `contractURI` function. I have implemented the DefaultOperatorFilter properly. The `contractURI` address is reachable as OpenSea is picking up the collection name and description and everything but not the `seller_fee_basis_points` and `fee_recepient`. It was working perfectly before Nov 8, but after implementing the `DefaultOperatorFilter` it is not working anymore. What could be the issue?

Here is a contract I have deployed to goerli and the creator earning informations are not being picked up.

https://goerli.etherscan.io/address/0x16e8255c88d0e24d99b5503467e03db9db722a63#code

**Comment by flametuner** [comment]
I have the same issue with mainnet contract. Everything from contractURI works fine besides `seller_fee_basis_points` and `fee_recepient`.

**Comment by Chkhikvadze** [comment]
I have the same issue with my contract can not seller_fee_basis_points and fee_recepient

https://goerli.etherscan.io/address/0xdaa48d1360a67be41743ca1a3d09e0d948a83674#readContract

**Comment by ashrhmn** [comment]
Have you guys found any workaround for this issue? I think it would have been better if we had a refresh option on the contract information too like we have for an NFT.

**Comment by operatorfilterer** [comment]
We can confirm issues with `contractURI()` method, and we're investigating

**Comment by flametuner** [comment]
> Have you guys found any workaround for this issue? I think it would have been better if we had a refresh option on the contract information too like we have for an NFT.

Right now, I need to update manually using the Ownable address

**Comment by F1roz** [comment]
I am Facing the same issue 
please fox it asap
thanks a lot

**Comment by F1roz** [comment]
> We can confirm issues with `contractURI()` method, and we're investigating

I am facing this same issue and thanks

**Comment by F1roz** [comment]
I am also facing issue on goerli, please fix asap. We are really close to the mainnet minting date

**Comment by ihorbond** [comment]
Same issue but it doesnt matter if the contract inherits DefaultOperatorFilter  or not. It's just broken.

**Comment by Slokh** [comment]
Sorry everyone, contractURI should be working again now.
