### ISSUE TITLE
Not working with TinyERC721 implementation

### ISSUE THREAD

**Issue by augustfr** [ProjectOpenSea/operator-filter-registry#33]
Does anyone know if this works with TinyERC721 (https://github.com/tajigen/tiny-erc721). 

I tried deploying with it on goerli and it still showed as unable to assign creator fees. But then when I switched to erc721a it worked.

Any ideas? 

TinyERC721 is very gas efficient which is why I like using it

**Comment by gasshadow** [comment]
how did you modify TinyERC721 contract?

**Comment by augustfr** [comment]
I didn't modify TinyERC721. I just used it as is instead of ERC721A

**Comment by operatorfilterer** [comment]
Validation on Goerli should be fixed now, apologies. Try re-deploying, or share your address here and we can re-validate!

**Comment by operatorfilterer** [comment]
Closing in lieu of #18 - please post any follow up in that issue.
