### ISSUE TITLE
Still showing contract is not eligible for Creator Fee

### ISSUE THREAD

**Issue by bayuec** [ProjectOpenSea/operator-filter-registry#35]
This is my contract address: 0x1b63Be0847C57f72cc8e093C99628D625C1F4baA on goerli network.
I checked [0x000000000000AAeB6D7670E522A718067333cd4E] and found my contract was registered the filter.
But the creator fee is still not eligible.
what's going on next?

**Comment by operatorfilterer** [comment]
Validating fees should be fixed in Goerli now, and we've re-validated your contract. You should be able to set fees now.

**Comment by operatorfilterer** [comment]
Closing in lieu of #18 - please post any follow up in that issue.
