### ISSUE TITLE
restrict via _beforeTokenTransfer?

### ISSUE THREAD

**Issue by greenish** [ProjectOpenSea/operator-filter-registry#41]
The example implementations for `ERC721` and `ERC1155` are restricting `safeTransferFrom` and `safeBatchTransferFrom` like this:
```
    function safeTransferFrom(address from, address to, uint256 tokenId, uint256 amount, bytes memory data)
        public
        override
        onlyAllowedOperator(from)
    {
        super.safeTransferFrom(from, to, tokenId, amount, data);
    }

    function safeBatchTransferFrom(
        address from,
        address to,
        uint256[] memory ids,
        uint256[] memory amounts,
        bytes memory data
    ) public virtual override onlyAllowedOperator(from) {
        super.safeBatchTransferFrom(from, to, ids, amounts, data);
    }
```

is there a reason to not restrict via `_beforeTokenTransfer`? 
```
    function _beforeTokenTransfer(
        address operator,
        address from,
        address to,
        uint[] memory ids,
        uint[] memory amounts,
        bytes memory data
    ) internal virtual override onlyAllowedOperator(from) {
        super._beforeTokenTransfer(operator, from, to, ids, amounts, data);
    }
```

**Comment by web3jt** [comment]
seems it will works well too, and save more gas? if u have logic in the `_beforeTokenTransfer`

**Comment by nidhhoggr** [comment]
It seems the downside of using `_beforeTokenTransfer` instead is that `_beforeTokenTransfer` is also called when minting, thus  unecessarily increasing gas fees on mints. Unlike minting, safeTransferFrom does not call `_beforeTokenTransfer`

**Comment by dievardump** [comment]
`_beforeTokenTransfer` is not part of EIP-721, it's only on some implementations of it

On top of that, in most of those implementations, if you are already in `_beforeTokenTransfer`, it means you already used quite some more gas to come there than if applied on a modifier

**Comment by web3jt** [comment]
> It seems the downside of using `_beforeTokenTransfer` instead is that `_beforeTokenTransfer` is also called when minting, thus unnecessarily increasing gas fees on mints.

Oh, yes, watse when minting, tkx for ur explain

**Comment by operatorfilterer** [comment]
As mentioned in this thread, `_beforeTokenTransfer` is not part of the EIP-721 specification, so the examples do not use them.

Developers are free to implement registry logic however they'd like, and can ensure compliance with the included validation tests.

**Comment by nidhhoggr** [comment]
@operatorfilterer EIP-721 conformity is irrelevant because your example includes an import for the OpenZeppelin ERC721 which DOES implement _beforeTokenTransfer.
> import {ERC721} from "openzeppelin-contracts/token/ERC721/ERC721.sol";

As such the real issue is that `_beforeTokenTransfer` is called on Mint.
