### ISSUE TITLE
Upgrade contract is not working

### ISSUE THREAD

**Issue by moonfunjohn** [ProjectOpenSea/operator-filter-registry#44]
I upgraded my ERC1155 contract yesterday but OpenSea still say "This collection is not eligible for creator fees" in the collection edit page.

I followed the example : https://github.com/ProjectOpenSea/operator-filter-registry/blob/main/src/example/upgradeable/ExampleERC1155Upgradeable.sol and added the following methods into my old contract

function setApprovalForAll(address operator, bool approved) public override onlyAllowedOperatorApproval(operator) {
        super.setApprovalForAll(operator, approved);
    }

    function safeTransferFrom(address from, address to, uint256 tokenId, uint256 amount, bytes memory data)
        public
        override
        onlyAllowedOperator(from)
    {
        super.safeTransferFrom(from, to, tokenId, amount, data);
    }

    function safeBatchTransferFrom(
        address from,
        address to,
        uint256[] memory ids,
        uint256[] memory amounts,
        bytes memory data
    ) public virtual override onlyAllowedOperator(from) {
        super.safeBatchTransferFrom(from, to, ids, amounts, data);
    }

After upgrading my old contract on Ethereum Mainnet, nothing changed in my collection editing page, it still say "This collection is not eligible for creator fees".

**Comment by Slokh** [comment]
What's the address?

**Comment by operatorfilterer** [comment]
Closing for now as we do not have a contract address to debug; please reopen if you're still having the issue and are able to provide a contract address.
