### ISSUE TITLE
Can we get a package so npm and yarn can import these contracts? 

### ISSUE THREAD

**Issue by audieleon** [ProjectOpenSea/operator-filter-registry#45]
Without a package, I'm left trying to copy these in. Are these contracts at the point they can be packaged up an hosted at npm?

**Comment by nidhhoggr** [comment]
https://www.npmjs.com/package/operator-filter-registry

**Comment by audieleon** [comment]
This is great, thank you. Is there a reason there aren't any releases listed in the repo here? That would have helped me locate it. I was looking for @ProjectOpenSea/operator-filter-registry.

**Comment by operatorfilterer** [comment]
The creator of that package has graciously transferred ownership to OpenSea, and we are hoping to publish the most recent versions and update the readme in the coming days.

**Comment by operatorfilterer** [comment]
Added to the repo and published the latest updates, thanks!
