### ISSUE TITLE
ERC721A not compatible

### ISSUE THREAD

**Issue by JOHNFFFEE** [ProjectOpenSea/operator-filter-registry#60]
Hi,
your package is not working with erc721A because the transfers functions and setApproval are payable.
please update your package to allow erc721A as well.
thanks

```TypeError: Overriding function changes state mutability from "nonpayable" to "payable".
```

**Comment by cstaelen** [comment]
Any feedback about this issue ? 
I encountered the same issue, @JOHNFFFEE did you fix it ?

**Comment by JOHNFFFEE** [comment]
Update the erc721a to its last version then make the functions ‘payable’

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
