### ISSUE TITLE
"This collection is not eligible for creator fees. Learn more" on collection with enforcement enabled

### ISSUE THREAD

**Issue by h8ku** [ProjectOpenSea/operator-filter-registry#61]
If a collection contract has enforcement disabled by default, 1X is minted, then enforcement is enabled, OS still does not see this being enabled and does not allow setting royalties.

Happened with this collection https://opensea.io/collection/strawberryjuice as an example

Add a recheck eligibility button next to creator fees?

**Comment by nidhhoggr** [comment]
I have the same issue. I'm curious, what was the resolution? When I check the collection on OpenSea it shows you have 5% creator fees which mean this has obviously since been resolved. So it's safe to assume this isn't an automated process? Or what?

**Comment by h8ku** [comment]
> I have the same issue. I'm curious, what was the resolution? When I check the collection on OpenSea it shows you have 5% creator fees which mean this has obviously since been resolved. So it's safe to assume this isn't an automated process? Or what?

If you have enforcement enabled now, contact OS and select the royalties option so they can refresh the collection.

**Comment by nidhhoggr** [comment]
I launched the contract with enforcements enabled. Did you get special treatment?

**Comment by h8ku** [comment]
> I launched the contract with enforcements enabled.

Contact them. Someone will check your collection and verify that it is setup correctly probably. Did your contract work right on testnet OS site?

> Did you get special treatment?

I contacted them after it was enabled and they said they refreshed the collection so then it would work.

**Comment by nidhhoggr** [comment]
Okay, yeah I can confirm I had to contact OpenSea and have them manually enable creator fees. Thanks.

**Comment by Slokh** [comment]
We have a refresh button on the collection settings page now
