### ISSUE TITLE
ERC1155 cannot buy on Opensea (Testnet Goerli)

### ISSUE THREAD

**Issue by 0xcielo** [ProjectOpenSea/operator-filter-registry#65]
I have a simple ERC1155 contract that extends DefaultOperatorFilterer.

It also define the contract URI function.

I can deploy and mint correctly.

I can sell it on opensea, but when I try to buy on testnet i recieve this message 'Execution reverted. Please reach out to the collection owner to troubleshoot.'.

Do I need to configure something more to work correctly?

**Comment by DaWe35** [comment]
No one can review the nothing, so please consider sending your source code to us, so bored devs while the OpenSea devs are somewhere else doing something more important I guess
