### ISSUE TITLE
Wrong default address for looksrare

### ISSUE THREAD

**Issue by zerosdontcount** [ProjectOpenSea/operator-filter-registry#7]
The example used in documentation blocked listing on x2y2 but not looksrare on ethereum mainnet. I thought the correct address might be 0xf42aa99F011A1fA7CDA90E5E98b277E306BcA83e (this is the contract you setApprovalForAll on looksrare listings) not 0x59728544b08ab483533076417fbbb2fd0b17ce3a which is listed in the documentation, though when I ran UpdateOperator, it still didn't block looksrare.

**Comment by operatorfilterer** [comment]
Fixed in 45bbc6955b7f89a8d4bba3473882cd6c1e3b9c94 / https://etherscan.io/tx/0x7e5ae58d89b7f10f0e2cd94fd1242bfe668a4c3448551e5d3647d7a70dce7c08

**Comment by zerosdontcount** [comment]
Even after this update and subscribed to your filter it let me list and purchase on Looksrare

**Comment by cxkoda** [comment]
`0xf42aa99F011A1fA7CDA90E5E98b277E306BcA83e` was not included in the transaction and is not in the denylist.
