### ISSUE TITLE
LooksRare still allows listing and selling even with new contract address

### ISSUE THREAD

**Issue by zerosdontcount** [ProjectOpenSea/operator-filter-registry#8]
It seems some new operator addresses were added for LooksRare (https://github.com/ProjectOpenSea/operator-filter-registry/issues/7), however it appears that listing, selling, and buying still works on LooksRare. 

tx: https://etherscan.io/tx/0x40d78b8381f03b8b6176bdc2277680d005679c0d2d78e1548f65268db96b057e

**Comment by cxkoda** [comment]
`0xf42aa99F011A1fA7CDA90E5E98b277E306BcA83e` was not included in the transaction as stated in #7 and is not in the denylist yet.

**Comment by zerosdontcount** [comment]
I'm sorry, I am not following, the transaction above is after `0xf42aa99F011A1fA7CDA90E5E98b277E306BcA83e` was added to the filter

**Comment by operatorfilterer** [comment]
Thanks for re-raising. Here is the new transaction - will keep open until we confirm.

https://etherscan.io/tx/0x3feb68f3426c9f07dbcea410456ed628ae5eab8d65d2be6161395543993294ba

**Comment by cxkoda** [comment]
looks good to me

**Comment by zerosdontcount** [comment]
Worked on mainnet after this update. Thank you. Users can list, but not purchase on LR, which makes sense since it edits the transfer event.
