### ISSUE TITLE
"Creator earnings" of ERC1155 can be edited.

### ISSUE THREAD

**Issue by KunihiroTakayanagi** [ProjectOpenSea/operator-filter-registry#82]
Hello to the OpenSea development team.

we have incorporated the DefaultOperatorFilterer into ERC1155 and deployed it to Goerli network.
we verified the sales on OpenSea's test net and was able to edit "Creatoer earnings".
![screen shot 2023-01-12 16 06 01](https://user-images.githubusercontent.com/77762518/212006135-f3088c39-be9c-4826-8cb8-596f9ad300e8.png)

Below is the verification code.
https://goerli.etherscan.io/address/0x3aa59d510abed17216c4c7da676862d8381e634b#code

Below is the OpenSea(testet) collection page.
https://testnets.opensea.io/ja/collection/unidentified-contract-baemdyveyr

Below is the transaction that was sold and successfully traded with the commission edited to 0%.
https://goerli.etherscan.io/tx/0xfd13270c2977b588b8256d6f719e4124b73a1d729b9bc1d3b10944c21331bd76

How can we disable the "creator earnings" edit when ERC1155 is offered for sale?
(When we tried with ERC721, the "Creatoer fearnigs" edits were disabled as expected.)

Thank you in advance for your help.

**Comment by KunihiroTakayanagi** [comment]
we tried on Mumbai network and same situation.
https://testnets.opensea.io/collection/unidentified-contract-mdk3qbqkbg
<img width="598" alt="スクリーンショット 2023-01-13 12 30 28" src="https://user-images.githubusercontent.com/77762518/212230995-d4e68907-2aec-4dd2-ad9e-62553adb6a55.png">

Fuji network too.
https://testnets.opensea.io/collection/unidentified-contract-bhb8eeyget
<img width="595" alt="スクリーンショット 2023-01-13 12 29 39" src="https://user-images.githubusercontent.com/77762518/212231047-47229bd8-cb5c-4886-8b42-35a8a20e9522.png">

**Comment by DaWe35** [comment]
Please share the source code of the contract and a screenshot about the collection edit page

**Comment by KunihiroTakayanagi** [comment]
@DaWe35
Thanks for your reply.

The source code is below.

``` solidity
// SPDX-License-Identifier: MIT
pragma solidity >=0.8.7 <0.9.0;

import "@openzeppelin/contracts/access/Ownable.sol";
import "@openzeppelin/contracts/token/ERC1155/extensions/ERC1155Supply.sol";
import "@openzeppelin/contracts/token/common/ERC2981.sol";
import "operator-filter-registry/src/DefaultOperatorFilterer.sol";

//---------------------
// ERC1155 Sample
//---------------------
contract Token is Ownable, ERC1155, ERC2981, DefaultOperatorFilterer {
    //-----------------------------------------
    // constant
    //-----------------------------------------
    uint96 constant private ROYALTY_FEE_NUMERATOR = 990;   // 9.9%

    //-----------------------------------------
    // strage
    //-----------------------------------------
    mapping( uint256 => string ) private _map_uri;

    //-----------------------------------------
    // [public] constructor
    //-----------------------------------------
    constructor() Ownable() ERC1155( "" ) {
        _setDefaultRoyalty( owner(), ROYALTY_FEE_NUMERATOR );
    }

    //=======================================================================
    // [public/override] 
    //=======================================================================
    function supportsInterface(bytes4 interfaceId) public view override( ERC1155, ERC2981 ) returns (bool) {
        return super.supportsInterface(interfaceId);
    }

    //=======================================================================
    // [external/onlyOwner] for ERC2981
    //=======================================================================
    function setDefaultRoyalty( address receiver, uint96 feeNumerator ) external onlyOwner { _setDefaultRoyalty( receiver, feeNumerator ); }
    function deleteDefaultRoyalty() external onlyOwner { _deleteDefaultRoyalty(); }
    function setTokenRoyalty( uint256 tokenId, address receiver, uint96 feeNumerator ) external onlyOwner { _setTokenRoyalty( tokenId, receiver, feeNumerator ); }
    function resetTokenRoyalty( uint256 tokenId ) external onlyOwner { _resetTokenRoyalty( tokenId ); }

    //=======================================================================
    // [public/override/onlyAllowedOperatorApproval] for OperatorFilter
    //=======================================================================
    function setApprovalForAll(address operator, bool approved) public override onlyAllowedOperatorApproval(operator) { super.setApprovalForAll(operator, approved); }
    function safeTransferFrom(address from, address to, uint256 tokenId, uint256 amount, bytes memory data) public override onlyAllowedOperator(from) { super.safeTransferFrom(from, to, tokenId, amount, data); }
    function safeBatchTransferFrom( address from, address to, uint256[] memory ids, uint256[] memory amounts, bytes memory data ) public virtual override onlyAllowedOperator(from) { super.safeBatchTransferFrom(from, to, ids, amounts, data); }

    //-----------------------------------------
    // [public/override] uri
    //-----------------------------------------
    function uri(uint256 tokenId ) public view virtual override returns (string memory) {
        return( _map_uri[tokenId] );
    }

    //-----------------------------------------
    // [external/onlyOwner] set uri
    //-----------------------------------------
    function setUri( uint256 tokenId, string calldata __uri ) external onlyOwner {
        _map_uri[tokenId] = __uri;
    }

    //-----------------------------------------
    // [external/onlyOwner] mint
    //-----------------------------------------
    function mintTokenWithAmount( uint256 tokenId, uint256 amount ) external onlyOwner {
        require( bytes(_map_uri[tokenId]).length > 0, "no uri" );
        require( amount > 0, "invalid amount" );

        _mint( msg.sender, tokenId, amount, "" );
    }
}
```

The verified code URL is below.
https://goerli.etherscan.io/address/0x3aa59d510abed17216c4c7da676862d8381e634b#code


The screenshots of the collection edit page are below.
<img width="1118" alt="ss00" src="https://user-images.githubusercontent.com/77762518/212448458-d153058c-dbfb-4516-939c-0b0ec4910877.png">

<img width="1074" alt="ss01" src="https://user-images.githubusercontent.com/77762518/212448496-dc297ab6-7151-4b16-8707-8ed0b758ef0c.png">

<img width="1004" alt="ss02" src="https://user-images.githubusercontent.com/77762518/212448501-7be87ffc-458e-4298-904c-bb5cb60757d0.png">

<img width="745" alt="ss03" src="https://user-images.githubusercontent.com/77762518/212448509-c5000231-7825-443f-a26a-13b771a01442.png">

<img width="831" alt="ss04" src="https://user-images.githubusercontent.com/77762518/212448518-5b01c322-7279-46e3-a3f8-6bb0454cea35.png">

<img width="781" alt="ss05" src="https://user-images.githubusercontent.com/77762518/212448527-f20ca46e-2605-4028-9664-d100301e91ab.png">

<img width="788" alt="ss06" src="https://user-images.githubusercontent.com/77762518/212448534-449729a2-2a18-468c-83a5-fa23386ca551.png">

Thank you very much.

**Comment by DaWe35** [comment]
Thanks @KunihiroTakayanagi,

As I see, OpenSea shows that creator fees are still optional for your contract, which indicates that the implementation of `operator-filter-registry` was not successful.

I made the same mistake first, so the issue is clearly the last part from https://github.com/ProjectOpenSea/operator-filter-registry#default-usage
You need to override the ERC721 transfer and approval methods. I was able to find 2 overwritten methods out of the 5 required, and also a third one I know nothing about. The point is, approve, and the 2 safeTransferFrom overwrites are missing from your contract and I believe this caused the issue.

When the issue is resolved, you'll see, this box will no longer appear: 
![image](https://user-images.githubusercontent.com/10603822/212500865-7f948f1b-b75e-402b-8631-8802a9dfe0ae.png)

Please don't forget to close the issue on GitHub, if resolved (I can't because I'm not related to the owners), otherwise feel free to ask more questions :)

**Comment by KunihiroTakayanagi** [comment]
@DaWe35 
Thanks for the reply.
Is your description in regards to ERC721?
ERC721 with the OperatorFilterer is working fine on our side.

Our problem is on ERC1155 with the OperatorFilterer.
We tried to implement with it by referring to the sample code below, but it is not working properly.
https://github.com/ProjectOpenSea/operator-filter-registry/blob/main/src/example/ExampleERC1155.sol

We wrote 3 functions that should be overridden.

``` solidity
    //=======================================================================
    // [public/override/onlyAllowedOperatorApproval] for OperatorFilter
    //=======================================================================
    function setApprovalForAll(address operator, bool approved) public override onlyAllowedOperatorApproval(operator) { super.setApprovalForAll(operator, approved); }
    function safeTransferFrom(address from, address to, uint256 tokenId, uint256 amount, bytes memory data) public override onlyAllowedOperator(from) { super.safeTransferFrom(from, to, tokenId, amount, data); }
    function safeBatchTransferFrom( address from, address to, uint256[] memory ids, uint256[] memory amounts, bytes memory data ) public virtual override onlyAllowedOperator(from) { super.safeBatchTransferFrom(from, to, ids, amounts, data); }
```

**Comment by DaWe35** [comment]
Ohh sorry, my bad. So basically you copied the whole example and it's not working. LOL

I still believe ERC1155 has `approve`, and `safeTransferFrom` functions too, hasn't it? If yes, you could try to overwrite them, maybe?

**Comment by KunihiroTakayanagi** [comment]
@DaWe35
Thanks for your reply.
We overrode the following functions related to "TRANSFERING NFTs" in ERC1155.

```
setApprovalForAll
safeTransferFrom
safeBatchTransferFrom
```

There should be no other functions to be overridden(only these 3 functions are overridden in the OpenSea's sample).

Looking at several past Issues, ERC1155 seems to be behaving suspiciously.Sometimes it doesn't work on the test net, sometimes it doesn't work on the main net.

https://github.com/ProjectOpenSea/operator-filter-registry/issues/36
https://github.com/ProjectOpenSea/operator-filter-registry/issues/81

Perhaps it is not a smart contract problem, but a problem on the OpenSea side (server?). If this is the case, we are hoping that some kind of fix will be made in time and the system will be working properly.

We will wait for a while.
Thanks a lot for your support.

**Comment by KunihiroTakayanagi** [comment]
Resolved.

It seems we needed to run [Refresh eligibility] on the edit page of the collection.
(ERC721 did not need to do this, but ERC1155 does?)
![スクリーンショット 2023-01-16 15 32 01](https://user-images.githubusercontent.com/77762518/212613570-4076b4a3-15be-4ca6-942a-9a519e672ab1.png)


It appears to be approved when the green check mark is placed.
![スクリーンショット 2023-01-16 15 32 11](https://user-images.githubusercontent.com/77762518/212613736-4a1674e1-7596-4e80-9405-96ea7a384ff2.png)


Then the [creator earnings] option disappeared on the NFT listing page.
![スクリーンショット 2023-01-16 15 31 14](https://user-images.githubusercontent.com/77762518/212613954-a41dab92-67b2-4546-be1e-d156f490b4bc.png)


This issue is closed.

**Comment by DaWe35** [comment]
Ohh wow, that's interesting. I assume you have a proxy contract, so you change the NFT contract instead of deploying a new one. Good to know.

**Comment by cryptospudz** [comment]
I'm having the same issue with my ERC1155 contract too, but I don't see a [Refresh eligibility] button on my collection edit page. I'm on https://testnets.opensea.io/ and my contract is on Polygon Mumbai. Is there any way to refresh the eligibility?

**Comment by KunihiroTakayanagi** [comment]
Hello @cryptospudz 

I have checked at 3 collections deployed a few days ago on Goerli, Mumbai and Fuji.

Only the Goerli collection displayed the "Refresh eligibility" button.
![スクリーンショット 2023-01-19 9 50 14](https://user-images.githubusercontent.com/77762518/213330766-5f9ac16f-1b99-4271-9342-7b780de03930.png)


However the "Refresh eligibility" button did not appear for the Mumbai and Fujii collections.
![スクリーンショット 2023-01-19 9 46 51](https://user-images.githubusercontent.com/77762518/213330795-94b56427-99d1-49b7-87e3-e12a12ff4d54.png)
![スクリーンショット 2023-01-19 9 48 03](https://user-images.githubusercontent.com/77762518/213330839-732f26f8-6c88-4fcd-9aa7-ce9a5a16c097.png)


The behavior may be different depending on the chains.
Please try deploying on Goerli.

**Comment by cryptospudz** [comment]
Thank you @KunihiroTakayanagi for your help. I tried Goerli and indeed the "Refresh eligibility" button appeared and clicking it enforced creator earnings. I tried Fuji too and strangely that worked automatically without any problems at all!
