### ISSUE TITLE
It is necessary to add support for upgradeable smart contracts

### ISSUE THREAD

**Issue by BedrosovaYulia** [ProjectOpenSea/operator-filter-registry#9]
It is necessary to add support for upgradeable smart contracts

**Comment by mwakkiy** [comment]
I too think we need to support upgradeable smart contracts.

**Comment by operatorfilterer** [comment]
Thanks for creating an issue! What problems are you encountering with integrating `OperatorFilterer` or `DefaultOperatorFilterer` into an upgradeable smart contract?
It's true that `ExampleERC721` and `ExampleERC1155` are not upgradeable, but they are intended only as examples of how to integrate the project into a new smart contract.

**Comment by BedrosovaYulia** [comment]
when i try to use DefaultOperatorFilterer in UUPS proxy implementation, Hardhat shows error: 

Error: Contract ... is not upgrade safe

contracts/DefaultOperatorFilterer.sol:9: Contract `DefaultOperatorFilterer` has a constructor
    Define an initializer instead
    https://zpl.in/upgrades/error-001

contracts/OperatorFilterer.sol:12: Contract `OperatorFilterer` has a constructor
    Define an initializer instead
    https://zpl.in/upgrades/error-001

**Comment by mwakkiy** [comment]
I want to use openzeppelin-upgrades.
There are some restrictions to do so.

https://github.com/OpenZeppelin/openzeppelin-upgrades

**Comment by operatorfilterer** [comment]
Thank you - we will be adding contracts that follow OpenZeppelin's upgradeable pattern sometime today.

**Comment by operatorfilterer** [comment]
This should be addressed with PR #13. Please reopen if you run into more issues.
